### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/argentina-reporting#19]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] l10n_ar_aeroo_base
- [ ] l10n_ar_aeroo_einvoice
- [ ] l10n_ar_aeroo_invoice
- [ ] l10n_ar_aeroo_payment_group
- [ ] l10n_ar_aeroo_purchase
- [ ] l10n_ar_aeroo_sale
- [ ] l10n_ar_aeroo_stock
- [ ] portal_sale_l10n_ar_aeroo_sale
